# Dataset Configuration
data:
  # Directory paths
  base_dir: data
  raw_dir: E:/BDMProject/raw
  processed_dir: data/processed
  images_dir: E:/BDMProject/images
  cache_dir: data/cache
  cache_features: true
  balanced_sampling: true
  max_text_length: 512
  vocab_size: 50000
  train_ratio: 0.7
  val_ratio: 0.15

  # Dataset-specific configurations
  fakeddit:
    files:
      - E:/BDMProject/raw/fakeddit/multimodal_train.tsv
      - E:/BDMProject/raw/fakeddit/multimodal_test_public.tsv
      - E:/BDMProject/raw/fakeddit/multimodal_validate.tsv
    label_mapping:
      real: 0
      fake: 1
    metadata_columns:
      - subreddit
      - created_utc
      - score
      - num_comments
      - upvote_ratio
    preprocessing:
      text:
        max_length: 512
        min_length: 10
      image:
        target_size: [224, 224]
        normalize: true

  fakenewnet:
    base_dir: E:/BDMProject/raw/fakenewnet
    sources: ["gossipcop", "politifact"]
    labels: ["fake", "real"]
    label_mapping:
      fake: 1
      real: 0
    metadata_columns:
      - url
      - title
      - authors
      - keywords
      - publish_date
      - source
      - summary
    preprocessing:
      text:
        max_length: 512
        min_length: 10
      image:
        target_size: [224, 224]
        normalize: true

# Model Configuration
model:
  text:
    embedding_dim: 300
    lstm_units: 128
    dropout_rate: 0.3

  image:
    input_shape: [224, 224, 3]
    backbone: "resnet50"
    trainable: false
    pooling: "avg"
    dropout_rate: 0.3

  fusion:
    hidden_units: [256, 128]
    dropout_rate: 0.3
    activation: "relu"
    output_activation: "sigmoid"

# Training Configuration
training:
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
  early_stopping_patience: 5
  reduce_lr_patience: 3
  reduce_lr_factor: 0.5
  min_lr: 0.00001

# Evaluation Configuration
evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1
  cross_dataset_validation: true
  save_predictions: true
  confusion_matrix: true
  classification_report: true

# Logging Configuration
logging:
  log_dir: logs
  tensorboard: true
  save_model: true
  save_history: true
  model_checkpoint: true
