# Slang and abbreviation dictionary for text preprocessing
# This file contains common internet slang, abbreviations, and their expansions

# Social media and internet slang
lol: "laugh out loud"
rofl: "rolling on the floor laughing"
lmao: "laughing my ass off"
omg: "oh my god"
wtf: "what the fuck"
btw: "by the way"
imo: "in my opinion"
imho: "in my humble opinion"
afaik: "as far as I know"
tbh: "to be honest"
idk: "I don't know"
smh: "shaking my head"
fyi: "for your information"
brb: "be right back"
ttyl: "talk to you later"
gtg: "got to go"
irl: "in real life"
yolo: "you only live once"
fomo: "fear of missing out"
til: "today I learned"
ftw: "for the win"
tbt: "throwback thursday"
bff: "best friends forever"
ot: "off topic"
tl;dr: "too long; didn't read"
eli5: "explain like I'm five"
ama: "ask me anything"
nsfw: "not safe for work"
nsfl: "not safe for life"
atm: "at the moment"
dm: "direct message"
pm: "private message"
fb: "facebook"
ig: "instagram"
yt: "youtube"
tik: "tiktok"
twt: "twitter"
rn: "right now"
bc: "because"
b/c: "because"
cuz: "because"
b4: "before"
ppl: "people"
u: "you"
ur: "your"
r: "are"
y: "why"
k: "okay"
thx: "thanks"
tx: "thanks"
tia: "thanks in advance"
congrats: "congratulations"
gratz: "congratulations"
convo: "conversation"
sry: "sorry"
plz: "please"
pls: "please"
def: "definitely"
prob: "probably"
v: "very"
mins: "minutes"
sec: "seconds"
hrs: "hours"
b/w: "between"
w/: "with"
w/o: "without"
deets: "details"
gonna: "going to"
wanna: "want to"
gotta: "got to"
dunno: "don't know"
whatev: "whatever"
cuz: "because"
hmm: "thinking"
tbf: "to be fair"
ngl: "not gonna lie"
gg: "good game"
bf: "boyfriend"
gf: "girlfriend"
asap: "as soon as possible"
faq: "frequently asked questions"
diy: "do it yourself"
nbd: "no big deal"
np: "no problem"
ty: "thank you"

# News and political terms
potus: "president of the united states"
scotus: "supreme court of the united states"
flotus: "first lady of the united states"
doj: "department of justice"
fbi: "federal bureau of investigation"
cia: "central intelligence agency"
nsa: "national security agency"
gop: "grand old party"
dnc: "democratic national committee"
wh: "white house"
msm: "mainstream media"
rw: "right wing"
lw: "left wing"

# Fake news related terms
clickbait: "attention-grabbing headline designed to generate clicks"
misinfo: "misinformation"
disinfo: "disinformation"
fakenews: "false news stories"
hoax: "deliberately fabricated falsehood"
conspiracy: "conspiracy theory"
truthers: "conspiracy theorists"

# Emojis and symbols
<3: "love"
</3: "broken heart"
:): "smile"
:(: "sad"
:D: "big smile"
:P: "tongue out"
:O: "surprised"
;): "wink"
xd: "laughing with eyes closed"
xoxo: "hugs and kisses" 